name: Issue Greeting Bot

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on new issue
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const user = issue.user.login;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              body: `Heyyy @${user} 👋

Thanks for opening this issue!

A maintainer will review it shortly. Please make sure you have:
- Clearly described the problem or feature request
- Added screenshots or logs (if applicable)
- Followed the issue template

📘 See **CONTRIBUTING.md** for contribution guidelines.

Thanks for helping improve **Magnamite-OTT** 🚀`
            });
